name: VSCode Extensions CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    run-tests:
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest]
                node-version: [16.x]
                vscode-version: [stable]

        name: Run unit tests
        runs-on: ${{ matrix.os }}

        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"

            - run: yarn install --immutable

            - name: Building packages
              run: yarn run build

            - name: Run tests
              run: yarn run test
